### Get All Persons
GET http://localhost:8080/ca1/api/person/
Accept: application/json


###
PUT http://localhost:8080/ca1/api/person/19
Content-Type: application/json

{
  "email": "mark@email.dk",
  "firstName": "Hans",
  "lastName": "Karl",
  "address": {
    "zip": 2800,
    "street": "Nørgaardsvej 30"}
}

###
POST http://localhost:8080/ca1/api/person/
Content-Type: application/json

{
  "email": "steen@email.dk",
  "firstName": "STEEN",
  "lastName": "Hans",
  "address": {
    "zip": 2600,
    "street": "Tisvej 4"
  },
  "phones": [
    {
      "phoneNumber": 12345678,
      "description": "WORK"
    }
  ],
  "hobbies": [
    {
      "name": "Generel",
      "wikiLink": "Håndværker",
      "category": "Indendørs",
      "type": "https://en.wikipedia.org/wiki/Acting"
    }
  ]
}

###
DELETE http://localhost:8080/ca1/api/person/9
Content-Type: application/json


