### Get All Persons
GET http://localhost:8080/ca/api/person/
Accept: application/json


###
PUT http://localhost:8080/ca/api/person/10
Content-Type: application/json

{
  "email": "mark@email.dk",
  "firstName": "Mark",
  "lastName": "Chomin",
  "address": {
    "zip": 2770,
    "street": "Zinni 10"
  },
  "phones": [
    {
      "phoneNumber": 29292929,
      "description": "HOME"
    }
  ],
  "hobbies": [
    {
      "name": "CS",
      "wikiLink": "https://en.wikipedia.org/wiki/CSGO",
      "category": "Generel",
      "type": "Indendørs"
    }
  ]
}

###
POST http://localhost:8080/ca/api/person/
Content-Type: application/json

{
  "email": "Fido@email.dk",
  "firstName": "Fido",
  "lastName": "Lele",
  "address": {
    "zip": 2770,
    "street": "Zinni 10"
  },
  "phones": [
    {
      "phoneNumber": 29292929,
      "description": "HOME"
    }
  ],
  "hobbies": [
    {
      "name": "Gaming",
      "wikiLink": "https://en.wikipedia.org/wiki/Gaming",
      "category": "Generel",
      "type": "Indendørs"
    }
  ]
}

###
DELETE http://localhost:8080/ca/api/person/10
Content-Type: application/json


